name: Dummy Algorithm Execution 

on: 
  push:
    paths:
      - 'algo_upload/**'

jobs:
  execute_algo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Execute modified or new script
      run: |
        for file in $(git diff --name-only HEAD-1 HEAD)
        do
          if [[ $file == algo_upload/*.py ]] then 
            python3 $file
          fi
        done
